INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (1, 'MADRID', 'BARCELONA', '10:00:00', '11:00:00');
  
INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (2, 'MADRID', 'ZARAGOZA', '10:30:00', '19:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (3, 'MADRID', 'TERUEL', '11:00:00', '11:05:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (4, 'MADRID', 'HUESCA', '12:00:00', '13:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (5, 'BARCELONA', 'ZARAGOZA', '12:00:00', '12:30:00');
  
INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (6, 'BARCELONA', 'MADRID', '13:00:00', '15:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (7, 'ZARAGOZA', 'MADRID', '13:00:00', '13:30:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (8, 'ZARAGOZA', 'TERUEL', '15:00:00', '18:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (9, 'ZARAGOZA', 'HUESCA', '13:00:00', '15:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (10, 'ZARAGOZA', 'BARCELONA', '18:00:00', '19:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (11, 'TERUEL', 'HUESCA', '15:00:00', '15:05:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (12, 'TERUEL', 'ZARAGOZA', '10:00:00', '17:00:00');

INSERT INTO CITY_LINK (ID, CITY, DESTINY_CITY, DEPARTURE_TIME, ARRIVAL_TIME) VALUES
  (13, 'HUESCA', 'ZARAGOZA', '17:00:00', '17:05:00');

